name: CI/CD for Lambda with Layer (No S3)

on:
  push:
    branches:
      - main

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Python (if needed)
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Zip Lambda function
      run: |
        mkdir package
        pip install -r layer/requirements.txt -t package/  # If you have dependencies
        cd package
        zip -r ../function.zip .
        cd ..
        zip -g function.zip lambda_function.py  # Add the main Lambda function code


    # Step 4: Zip the Lambda function code
    - name: Package Lambda Function
      run: |
        zip -r function.zip . -i lambda_function.py  # Replace with your Lambda entry file

    # Step 5: Configure AWS credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AccessKey }}
        aws-secret-access-key: ${{ secrets.SecretKey }}
        aws-region: us-east-1
        
    - name: List the contents of the ZIP file
      run: unzip -l function.zip

    # Step 6: Publish the Lambda layer
    - name: Publish Lambda Layer
      id: publish-layer
      run: |
        LAYER_ARN=$(aws lambda publish-layer-version \
          --layer-name my-python-layer \
          --zip-file fileb://layer.zip \
          --compatible-runtimes python3.13 \
          --query LayerVersionArn --output text)
        echo "LAYER_ARN=${LAYER_ARN}" >> $GITHUB_ENV

    # Step 7: Update the Lambda function
    - name: Deploy Lambda Function
      run: |
        aws lambda update-function-code --function-name Layer-function --zip-file fileb://function.zip
        aws lambda update-function-configuration --function-name Layer-function --layers $LAYER_ARN

#Line 
